### ISSUE TITLE
Podspec issue?

### ISSUE THREAD

**Issue by nishal** [nealyoung/NYAlertViewController#3]
[!] Unable to satisfy the following requirements:
- `NYAlertViewController` required by `Podfile`
- `NYAlertViewController` required by `Podfile`
- `NYAlertViewController` required by `Podfile`

**Comment by nealyoung** [comment]
Can you post your Podfile? I just installed the pod on one of my own projects, and it worked as expected. Perhaps try updating to the latest version of CocoaPods and running `pod update`.

**Comment by nishal** [comment]
Apologise for my ignorance. Seems like the version is too high, my Podfile needs iOS 6.0 and up and your library seems to be iOS 8.0 and up. I found another library CPNPopupController, but seems they too have a 7.0 and up limitation. So looks like I will have to either copy the .h & .m files and check if they work on iOS 6, if not then I'll have a lot more work to get a custom alert popup.
