### ISSUE TITLE
How can I add TextField in the alert view and able to enter text and retrieve it? Can you add this?

### ISSUE THREAD

**Issue by imran20487** [nealyoung/NYAlertViewController#5]

**Comment by nealyoung** [comment]
I've just released version 1.1.0 on GitHub and CocoaPods which adds support for adding text fields to an alert view with:

``` objc
- (void)addTextFieldWithConfigurationHandler:(void (^)(UITextField *textField))configurationHandler;
```

Alternatively, you can add text fields by adding them to a custom content view, and setting the alert view's content view property.
