### ISSUE TITLE
IOS7  cause AutoLayout issue！

### ISSUE THREAD

**Issue by Marlonzl** [nealyoung/NYAlertViewController#8]
ultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x14d9eeb0 V:|-(NSSpace(20))-[UILabel:0x14e71890]   (Names: '|':UIView:0x14e717b0 )>",
    "<NSLayoutConstraint:0x14d69fc0 V:[UILabel:0x14e71890]-(2)-[NYAlertTextView:0x15b68200]>",
    "<NSLayoutConstraint:0x14d3e400 V:[NYAlertTextView:0x15b68200]-(0)-[UIView:0x14e7d1a0]>",
    "<NSLayoutConstraint:0x14d78910 V:[UIView:0x14e7d1a0]-(0)-[UIView:0x14e71560]>",
    "<NSLayoutConstraint:0x14db66b0 V:[UIView:0x14e71560]-(0)-[UIView:0x14e6fb90]>",
    "<NSLayoutConstraint:0x14d72630 V:[UIView:0x14e6fb90]-(NSSpace(20))-|   (Names: '|':UIView:0x14e717b0 )>",
    "<NSLayoutConstraint:0x14e6fac0 UIView:0x14e717b0.height <= 0.9*NYAlertView:0x14e714a0.height>",
    "<NSAutoresizingMaskLayoutConstraint:0x14dccaa0 h=--& v=--& V:[NYAlertView:0x14e714a0(0)]>"
)

**Comment by nealyoung** [comment]
This project uses the UIPresentationController API, which is only available in iOS 8 and later.
